# Generated by Django 5.1.5 on 2025-02-01 16:44

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('msg_from', models.CharField(max_length=255)),
                ('msg_to', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
